const pages = {
    home: `<section class="page-section"><div class="hero terminal-frame"><h1>SUBJECT: JACK COLLINS</h1><p class="subtitle">STATUS: RESEARCH ASSOCIATE | POSITION: GAME DEVELOPER</p></div><div class="bio-section"><h3>PERSONNEL BIO</h3><p>Welcome to the Black Mesa Research Facility secure portal. I am a Game Developer specializing in immersive systems and technical design.</p></div><div class="links-section"><a href=\"https://www.linkedin.com/in/jack-collins-gaming/\" target=\"_blank\" class=\"diegetic-button-static\">LINKEDIN_PORTAL.EXE</a><a href=\"https://github.com/JackDevCollins\" target=\"_blank\" class=\"diegetic-button-static\">GITHUB_REPOS.EXE</a></div></section>`,
    work: `<section class="page-section"><h2>INDIVIDUAL ASSIGNMENTS</h2><div class="work-grid"><div class="work-card terminal-frame"><h3>PROJECT: DFS1</h3><div class="media-container" id="dfs1-media"><img src="images/placeholder.png" alt="DFS1 Media" class="current-media"><div class="media-controls"><button class="diegetic-button-static mini" id="cycle-dfs1">CYCLE_MEDIA</button></div></div><div class="description"><p>Project DFS1 involves the implementation of advanced spatial algorithms and navigation systems.</p></div></div></div></section>`,
    team: `<section class="page-section"><h2>TEAM COLLABORATIONS</h2><div class="team-sections"><div class="team-project terminal-frame"><h3>PROJECT ALPHA: ANOMALOUS MATERIALS</h3><div class="gallery-container"><div class="gallery-scroll"><img src="images/placeholder.png" alt="Slide 1"><img src="images/placeholder.png" alt="Slide 2"></div></div><p>Cooperative development of resonance cascade containment systems.</p></div></div></section>`,
    personal: `<section class="page-section"><h2>PERSONNEL DOSSIER</h2><div class="dossier-grid"><div class="dossier-left"><img src="images/placeholder.png" alt="Jack Collins" class="portrait terminal-frame"><div class="info-block"><p><strong>NAME:</strong> JACK COLLINS</p><p><strong>CLEARANCE:</strong> LEVEL 4</p><p><strong>DEPT:</strong> GAME DEVELOPMENT</p></div></div><div class="dossier-right"><h3>DOCUMENTS</h3><div class="doc-links"><a href=\"resume.pdf\" download class=\"diegetic-button-static\">DOWNLOAD_RESUME.PDF</a></div><div class="cover-letter-preview terminal-frame"><p>To the Black Mesa Recruitment Board... I am writing to express my interest in the Game Developer position.</p></div></div></div></section>`
};
function loadPage(p){ const a=document.getElementById("content-area"); if(!a)return; a.innerHTML=pages[p]||"<h1>404</h1>"; document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active")); const act=document.getElementById("nav-"+p); if(act)act.classList.add("active"); if(p==="work"){const c=document.getElementById("cycle-dfs1"); if(c)c.onclick=()=>cycleMedia("dfs1");} a.scrollTop=0; }
const mediaAssets={dfs1:["images/placeholder.png","images/placeholder2.png"]}; let mediaIndex={dfs1:0};
function cycleMedia(id){ const img=document.querySelector("#"+id+"-media img"); if(!img)return; mediaIndex[id]=(mediaIndex[id]+1)%mediaAssets[id].length; img.src=mediaAssets[id][mediaIndex[id]]; }
document.addEventListener("DOMContentLoaded",()=>{ document.querySelectorAll(".nav-btn").forEach(b=>{ b.addEventListener("click",()=>loadPage(b.getAttribute("data-page"))); }); loadPage("home"); });
